### ISSUE TITLE
Smaller size Plated Hole test points

### ISSUE THREAD

**Issue by jophut** [KiCad/Connectors_TestPoints.pretty#4]
I was looking for a 1.0mm plated hole test-point, but plated holes start at 2.0mm
I see the THTPad_d1.0mm but that is non-plated?!?
Now I am confused, a trough-hole pad, but non-plated, what's the purpose of that?

To me the following footprints seem to be missing:
* Test_Point_Plated_Hole_d1.0mm (with a size of 1.5mm)
* Test_Point_Plated_Hole_d1.5mm (with a size of 2.0mm)
Shall I make those?

**Comment by SchrodingersGat** [comment]
@jkriege2 did you script these ones or make them manually?

If a) then the script should be updated to include these
If b) then @jophut can contribute these :)

**Comment by jkriege2** [comment]
b) ... i.e. just go ahead and add whatever you want ;-)

JAN

**Comment by SchrodingersGat** [comment]
@jophut anything further to add to this issue, or can we close it?

**Comment by jophut** [comment]
b) I will submit a pull request the next time I'll be working with these footprints.
So this can be closed.
